application: listsv2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /bower_components
  static_dir: bower_components

- url: /elements
  static_dir: elements

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: guestbook.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
